/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Group;
import Classes.Task;
import Classes.User;
import com.mongodb.BasicDBObject;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Map;
import org.bson.Document;
import org.bson.conversions.Bson;
import org.bson.types.ObjectId;


public class Register extends javax.swing.JFrame {
    int xMouse, yMouse;
    static MongoClient client;
    
    
    public Register(MongoClient client) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.client = client;
        
        errorLabel.setText("");
        inputPassword.setEchoChar((char) 0);
        inputConfirmPassword.setEchoChar((char) 0);
        exit.setFocusable(false);
        minimize.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        inputUser = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        inputConfirmPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(246, 246, 246));
        header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(252, 252, 252));
        exit.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        exit.setText("X");
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        header.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        minimize.setBackground(new java.awt.Color(252, 252, 252));
        minimize.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        minimize.setText("-");
        minimize.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 0, 0)));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        header.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, 20));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Crear nuevo usuario");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        register.setBackground(new java.awt.Color(243, 243, 243));
        register.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        register.setText("Registrarse");
        register.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerMouseExited(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        background.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 90, 30));

        jLabel3.setText("Ya eres usuario?");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, 20));

        login.setForeground(new java.awt.Color(51, 51, 255));
        login.setText("Inicia sesion");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        background.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 80, 20));

        inputEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        inputEmail.setForeground(new java.awt.Color(153, 153, 153));
        inputEmail.setText("Ingrese correo electronico");
        inputEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        inputEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputEmailFocusLost(evt);
            }
        });
        background.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 290, 30));

        inputUser.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        inputUser.setForeground(new java.awt.Color(153, 153, 153));
        inputUser.setText("Ingrese el nombre de usuario");
        inputUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        inputUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputUserFocusLost(evt);
            }
        });
        background.add(inputUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 290, 30));

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("Error Label");
        background.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        inputPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        inputPassword.setForeground(new java.awt.Color(153, 153, 153));
        inputPassword.setText("Ingrese contraseña");
        inputPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        inputPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputPasswordFocusLost(evt);
            }
        });
        background.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 290, 30));

        inputConfirmPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        inputConfirmPassword.setForeground(new java.awt.Color(153, 153, 153));
        inputConfirmPassword.setText("Confirmar contraseña");
        inputConfirmPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        inputConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputConfirmPasswordFocusLost(evt);
            }
        });
        background.add(inputConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.red);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBackground(new Color(252, 252, 252));
    }//GEN-LAST:event_exitMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setBackground(new Color(235, 235, 235));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setBackground(new Color(252, 252, 252));
    }//GEN-LAST:event_minimizeMouseExited

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setForeground(new Color(0, 0, 153));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setForeground(new Color(51, 51, 255));
    }//GEN-LAST:event_loginMouseExited

    private void registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseEntered
        register.setBackground(new Color(235, 235, 235));
    }//GEN-LAST:event_registerMouseEntered

    private void registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseExited
        register.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_registerMouseExited

    private void inputEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusGained
        if(inputEmail.getText().equals("Ingrese correo electronico")){
            inputEmail.setText("");
            inputEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_inputEmailFocusGained

    private void inputEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputEmailFocusLost
        if(inputEmail.getText().isBlank()){
            inputEmail.setText("Ingrese correo electronico");
            inputEmail.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_inputEmailFocusLost

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        this.dispose();
        new Login(client).setVisible(true);
    }//GEN-LAST:event_loginMouseClicked

    private void inputUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUserFocusGained
        if(inputUser.getText().equals("Ingrese el nombre de usuario")){
            inputUser.setText("");
            inputUser.setForeground(Color.black);
        }
    }//GEN-LAST:event_inputUserFocusGained

    private void inputUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUserFocusLost
        if(inputUser.getText().isBlank()){
            inputUser.setText("Ingrese el nombre de usuario");
            inputUser.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_inputUserFocusLost

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        errorLabel.setText("");
        String user = inputUser.getText();
        String email = inputEmail.getText();
        String password = inputPassword.getText();
        String confirmPassword = inputConfirmPassword.getText();
        
        if(user.equals("Ingrese el nombre de usuario") || user.isBlank()){
            errorLabel.setText("Error: Ingrese todos los campos del formulario");
        }
        else if(email.equals("Ingrese correo electronico") || email.isBlank()){
            errorLabel.setText("Error: Ingrese todos los campos del formulario");
        }
        else if(password.equals("Ingrese contraseña") || password.isBlank()){
            errorLabel.setText("Error: Ingrese todos los campos del formulario");
        }
        else if(password.length() < 8){
            errorLabel.setText("Error: contraseña muy corta");
        }
        else if(confirmPassword.equals("Confirmar contraseña") || confirmPassword.isBlank()){
            errorLabel.setText("Error: Ingrese todos los campos del formulario");
        }
        else if(!email.contains("@gmail.com") && !email.contains("@hotmail.com") && 
                !email.contains("@correo.unimet.edu.ve") && !email.contains("@outlook.com")){
            errorLabel.setText("Error: correo no valido");
        }
        else if(!password.equals(confirmPassword)){
            errorLabel.setText("Error: confirme la contraseña");
        }
        else{
            MongoDatabase dataBase = client.getDatabase("cowork");

            MongoCollection users = dataBase.getCollection("users");
                        
            Bson filter = Filters.eq("email", email);
            
            FindIterable<Document> result = users.find(filter);
            
            boolean canRegister = true;
            for(Document doc: result){                
                String emailDoc = (String) doc.get("email");
                if(emailDoc.equals(email)){
                    errorLabel.setText("Email ya registrado");
                    canRegister = false;
                }                
            }
            
            if(canRegister){                
                Document newUser = new Document("_id", new ObjectId())
                        .append("name", user)
                        .append("email", email)
                        .append("password", password)
                        .append("groups", new ArrayList<Group>())
                        .append("tasks", new ArrayList<Task>());   
                
                users.insertOne(newUser);
                
                User currentUser = new User(user, email, new ArrayList<Group>(), new ArrayList<Task>());
                this.dispose();
                new MainMenu(currentUser).setVisible(true);
            }
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_registerActionPerformed

    private void inputPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPasswordFocusGained
        if(inputPassword.getText().equals("Ingrese contraseña")){
            inputPassword.setEchoChar('\u2022');
            inputPassword.setText("");
            inputPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_inputPasswordFocusGained

    private void inputPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPasswordFocusLost
        if(inputPassword.getText().isBlank()){
            inputPassword.setEchoChar((char) 0);
            inputPassword.setText("Ingrese contraseña");
            inputPassword.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_inputPasswordFocusLost

    private void inputConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputConfirmPasswordFocusGained
        if(inputConfirmPassword.getText().equals("Confirmar contraseña")){
            inputConfirmPassword.setEchoChar('\u2022');
            inputConfirmPassword.setText("");
            inputConfirmPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_inputConfirmPasswordFocusGained

    private void inputConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputConfirmPasswordFocusLost
        if(inputConfirmPassword.getText().isBlank()){
            inputConfirmPassword.setEchoChar((char) 0);
            inputConfirmPassword.setText("Confirmar contraseña");
            inputConfirmPassword.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_inputConfirmPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register(client).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton exit;
    private javax.swing.JPanel header;
    private javax.swing.JPasswordField inputConfirmPassword;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel login;
    private javax.swing.JButton minimize;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
