/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.JPanels;

import Classes.Group;
import Classes.User;
import static GUI.JPanels.TaskPanel.client;
import static GUI.JPanels.TaskPanel.currentUser;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.bson.Document;

/**
 *
 * @author mairo
 */
public class ShowTasks extends javax.swing.JPanel {
    static User currentUser;    
    static MongoClient client;
    
    public ShowTasks(User currentUser, MongoClient client) {
        initComponents();
        this.currentUser = currentUser;
        this.client = client;
        setLayout(new GridBagLayout());
        
        initTasks();
    }
    
    private void initTasks(){
       MongoDatabase dataBase = client.getDatabase("cowork");
        MongoCollection groups = dataBase.getCollection("groups");
        
        FindIterable<Document> groupDocs = groups.find();
        ArrayList<Document> allGroups = new ArrayList();
        
        for(Document groupDoc: groupDocs){            
            ArrayList<Document> auxMembers = (ArrayList<Document>) groupDoc.get("members");
            
            for(Document member: auxMembers){
                if(member.get("email").equals(currentUser.getEmail())){
                    allGroups.add(groupDoc);
                }
            }
        }
        
        for(Document groupDoc: allGroups){
            ArrayList<Document> tasksDocs = (ArrayList<Document>) groupDoc.get("tasks");
            
            int i = 0;
            for(Document tasksDoc: tasksDocs){
                GridBagConstraints gbc = new GridBagConstraints();
                gbc.fill = GridBagConstraints.BOTH; 
                gbc.insets = new Insets(5, 5, 5, 5); 
                
                String taskName = (String) tasksDoc.get("taskName");
                String groupName = (String) groupDoc.get("nameGroup");
                JPanel panel = createTaskPanel((String) tasksDoc.get("idTask"));
                gbc.gridx = i % 4; 
                gbc.gridy = i / 4;
                add(panel, gbc);
                i++;
            }
        } 
    }
    
    private JPanel createTaskPanel(String idTask){
        TaskPanel panel = new TaskPanel(idTask, currentUser, client);
        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
