/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.JPanels;

import Classes.Group;
import Classes.User;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.awt.Color;
import java.util.ArrayList;
import org.bson.Document;

/**
 *
 * @author mairo
 */
public class ShowCreateGroups extends javax.swing.JPanel {
    User currentUser;
    MongoClient client;
    
    public ShowCreateGroups(User currentUser, MongoClient client) {
        initComponents();
        this.currentUser = currentUser;
        this.client = client;
        
        String[] colors = {"Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Morado"};
        for(String color: colors){
            inputColors.addItem(color);
        }
        inputColors.setEditable(false);
        
        errorLabel.setText("");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputGroupName = new javax.swing.JTextField();
        inputColors = new javax.swing.JComboBox<>();
        create = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(620, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(inputGroupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 280, -1));

        inputColors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Naranja", "Amarillo", "Verde", "Azul", "Morado" }));
        add(inputColors, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 280, -1));

        create.setText("Crear");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("Error Label");
        add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel1.setText("Ingrese el nombre del grupo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel2.setText("Ingrese color del grupo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        errorLabel.setForeground(Color.red);
        errorLabel.setText("");
        
        String groupName = inputGroupName.getText();
        String groupColor = (String) inputColors.getSelectedItem();
        
        if(groupName.isBlank() || groupColor.isBlank()){
            errorLabel.setText("Error: ingrese todos los campos del formulario");
        }
        else{
            
            MongoDatabase dataBase = client.getDatabase("cowork");
            MongoCollection users = dataBase.getCollection("users");
            MongoCollection groups = dataBase.getCollection("groups");
            
            Document queryGroup = new Document("nameGroup", groupName);            
            Document resultGroup = (Document) groups.find(queryGroup).first();
            
            if(resultGroup == null){
                
                ArrayList members = new ArrayList();
                
                Document queryUser = new Document("email", currentUser.getEmail());
                Document resultUser = (Document) users.find(queryUser).first();
                
                members.add(resultUser);
                
                Document newGroupDoc = new Document("nameGroup", groupName)
                        .append("leader", currentUser.getEmail())
                        .append("members", members)
                        .append("tasks", new ArrayList<>())
                        .append("colorGroup", groupColor);
                
                groups.insertOne(newGroupDoc);
                errorLabel.setForeground(Color.green);
                errorLabel.setText("Grupo creado con exito!");
                                                                                                                  }
            else{
                System.out.println("Si existe");
            }
            
        }
        
    }//GEN-LAST:event_createActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JComboBox<String> inputColors;
    private javax.swing.JTextField inputGroupName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
